# Exploratory Data Analysis

## 1.Introduction

## 2.Importing the important libraries

In [9]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from data_ingest import IngestData

## 3.Reading Data

In [17]:
ingest_data = IngestData()
data = ingest_data.get_data('ols-regression-dataset/data/cancer_reg.csv')

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf1 in position 41137: invalid continuation byte

## 4.Basic Data Exploration

In [13]:
data.head()

,avganncount,avgdeathsperyear,target_deathrate,incidencerate,medincome,popest2015,povertypercent,studypercap,binnedinc,medianage,...,pctprivatecoveragealone,pctempprivcoverage,pctpubliccoverage,pctpubliccoveragealone,pctwhite,pctblack,pctasian,pctotherrace,pctmarriedhouseholds,birthrate
0,1397.0,469,164.9,489.8,61898,260131,11.2,499.748204,"(61494.5, 125635]",39.3,...,NaN,41.6,32.9,14.0,81.780529,2.594728,4.821857,1.843479,52.856076,6.118831
1,173.0,70,161.3,411.6,48127,43269,18.6,23.111234,"(48021.6, 51046.4]",33.0,...,53.8,43.6,31.1,15.3,89.228509,0.969102,2.246233,3.741352,45.372500,4.333096
2,102.0,50,174.7,349.7,49348,21026,14.6,47.560164,"(48021.6, 51046.4]",45.0,...,43.5,34.9,42.1,21.1,90.922190,0.739673,0.465898,2.747358,54.444868,3.729488
3,427.0,202,194.8,430.4,44243,75882,17.1,342.637253,"(42724.4, 45201]",42.8,...,40.3,35.0,45.3,25.0,91.744686,0.782626,1.161359,1.362643,51.021514,4.603841
4,57.0,26,144.4,350.1,49955,10321,12.5,0.000000,"(48021.6, 51046.4]",48.3,...,43.9,35.1,44.0,22.7,94.104024,0.270192,0.665830,0.492135,54.027460,6.796657

In [16]:
data.describe
print(data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3047 entries, 0 to 3046
Data columns (total 34 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   avganncount              3047 non-null   float64
 1   avgdeathsperyear         3047 non-null   int64
 2   target_deathrate         3047 non-null   float64
 3   incidencerate            3047 non-null   float64
 4   medincome                3047 non-null   int64
 5   popest2015               3047 non-null   int64
 6   povertypercent           3047 non-null   float64
 7   studypercap              3047 non-null   float64
 8   binnedinc                3047 non-null   object
 9   medianage                3047 non-null   float64
 10  medianagemale            3047 non-null   float64
 11  medianagefemale          3047 non-null   float64
 12  geography                3047 non-null   object
 13  avghouseholdsize         3047 non-null   float64
 14  percentmarried           3047 non-null   float64
 15  pctnohs18_24             3047 non-null   float64
 16  pcths18_24               3047 non-null   float64
 17  pctsomecol18_24          762 non-null    float64
 18  pctbachdeg18_24          3047 non-null   float64
 19  pcths25_over             3047 non-null   float64
 20  pctbachdeg25_over        3047 non-null   float64
 21  pctemployed16_over       2895 non-null   float64
 22  pctunemployed16_over     3047 non-null   float64
 23  pctprivatecoverage       3047 non-null   float64
 24  pctprivatecoveragealone  2438 non-null   float64
 25  pctempprivcoverage       3047 non-null   float64
 26  pctpubliccoverage        3047 non-null   float64
 27  pctpubliccoveragealone   3047 non-null   float64
 28  pctwhite                 3047 non-null   float64
 29  pctblack                 3047 non-null   float64
 30  pctasian                 3047 non-null   float64
 31  pctotherrace             3047 non-null   float64
 32  pctmarriedhouseholds     3047 non-null   float64
 33  birthrate                3047 non-null   float64
dtypes: float64(29), int64(3), object(2)
memory usage: 809.5+ KB
None